# Generated by Django 4.1.7 on 2023-03-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='number_pages',
            field=models.SmallIntegerField(default=0),
        ),
    ]
