# Generated by Django 4.1.7 on 2023-03-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='rental_user',
            new_name='registration_user',
        ),
    ]
