# Generated by Django 4.1.7 on 2023-03-13 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rename_rental_user_rental_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='return_period',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 19, 14, 54, 656607)),
        ),
    ]
