# Generated by Django 4.1.7 on 2023-03-16 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_rental_amount_paid_alter_rental_return_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_period',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 14, 43, 1, 79872)),
        ),
    ]
