# Generated by Django 4.1.7 on 2023-03-12 19:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('document', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d/')),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now)),
                ('registration_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_registration_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
