# Generated by Django 4.1.7 on 2023-03-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='title',
        ),
    ]
